### DISCUSSION TITLE
20240704 Weekly Development Meeting

### DISCUSSION THREAD

**Discussion by josecelano** [nautilus-cyberneering/.github#101] [Meetings]
- Time:  9:30 in Canary Islands (WET (UTC+0)).
- Time: 10:30 in Vaduz (CET (UTC+1)).

Location:
<https://meeting.blockfinance-eco.li/NautilusCyberneeringWeeklyDevMeeting>

Expected duration: 2 to 4 hours with breaks

Communicated attendants:

- Cameron Garnham(@da2ce7)  - 
- Jose Celano(@josecelano) - x
- Constantin Bosse(@cgbosse) - x
- Mario Melchor(@mario-nt) - x
- Graeme Byrne(@grmbyrn) - x

-------------------------------------------------------------

## Agenda:

1. Everyone will take their turn and:
- Go over his notes added as comments for the meeting which will have been added in advance to give an update of all the work done during the previous week indicating.
	- The issues worked on
	- The progress made on them
	- Other things done
- Inform of any faced challenges and request help if necessary to work on specific issues.
- Highlight the encountered difficulties, especially if there is a risk of them causing delays or affecting end product's quality.
- Communicate what will be the next week's tasks.
- List any new topics for further discussion in an additional Technical meeting that he noted for future discussion in comments to this discussion either before the meeting or after his turn so that they get considered.

During the meeting every team member will take their turns and follow this sequence.
The topics for further discussion will be noted in advance by each the team member and to the meetings agenda.

2. At the end of the meeting if there any new technical topics to be discussed further it will be decided to
set another meeting date for the discussion of these or to hold the meeting hereafter.

Also the persons to be part of the meeting will be decided on so that the others will be free to continue their own work.

**Comment by josecelano** [comment]
I've been implementing some improvements in the configuration of the Tracker and Index proposed by @da2ce7. I'm still waiting for feedback on three of them:

- https://github.com/torrust/torrust-index/issues/653
- https://github.com/torrust/torrust-index/issues/654
- https://github.com/torrust/torrust-tracker/issues/938

### Torrust Tracker

- https://github.com/torrust/torrust-tracker/issues/918
- Update dependencies

Changes in the configuration:

- https://github.com/torrust/torrust-tracker/issues/932
- https://github.com/torrust/torrust-tracker/issues/935
- https://github.com/torrust/torrust-tracker/issues/936
- https://github.com/torrust/torrust-tracker/issues/937 
- https://github.com/torrust/torrust-tracker/issues/939

### Torrust Index

- https://github.com/torrust/torrust-index/issues/648
- Update dependencies

Changes in the configuration:

  - https://github.com/torrust/torrust-index/issues/651
  - https://github.com/torrust/torrust-index/issues/652
  - https://github.com/torrust/torrust-index/issues/655
  - https://github.com/torrust/torrust-index/issues/657

### Torrust Index GUI

- https://github.com/torrust/torrust-index-gui/issues/581

### Torrust Demo

- https://github.com/torrust/torrust-demo/issues/8

### Torrust Compose

- https://github.com/torrust/torrust-compose/issues/22

**Reply by josecelano** [reply]
The current version of the tracker:

```toml
version = "2"

[logging]
threshold = "info"

[core]
inactive_peer_cleanup_interval = 600
listed = false
private = false
tracker_usage_statistics = true

  [core.announce_policy]
  interval = 120
  interval_min = 120

  [core.database]
  driver = "Sqlite3"
  path = "./storage/tracker/lib/database/sqlite3.db"

  [core.net]
  external_ip = "0.0.0.0"
  on_reverse_proxy = false

  [core.tracker_policy]
  max_peer_timeout = 900
  persistent_torrent_completed_stat = false
  remove_peerless_torrents = true

[[udp_trackers]]
bind_address = "0.0.0.0:6969"

[[http_trackers]]
bind_address = "0.0.0.0:7070"

[http_api]
bind_address = "0.0.0.0:1212"

  [http_api.access_tokens]
  admin = "MyAccessToken"

[health_check_api]
bind_address = "127.0.0.1:1313"
```

The current version of the index:

```toml
version = "2"

[logging]
threshold = "info"

[website]
name = "Torrust"

[tracker]
api_url = "http://localhost:1212/"
listed = false
private = false
token = "***"
token_valid_seconds = 7_257_600
url = "udp://localhost:6969"

[net]
bind_address = "0.0.0.0:3001"

[auth]
email_on_signup = "optional"
secret_key = "***"

  [auth.password_constraints]
  max_password_length = 64
  min_password_length = 6

[database]
connect_url = "sqlite://data.db?mode=rwc"

[mail]
email_verification_enabled = false
from = "example@email.com"
reply_to = "noreply@email.com"

  [mail.smtp]
  port = 25
  server = ""

    [mail.smtp.credentials]
    password = "***"
    username = ""

[image_cache]
capacity = 128_000_000
entry_size_limit = 4_000_000
max_request_timeout_ms = 1_000
user_quota_bytes = 64_000_000
user_quota_period_seconds = 3_600

[api]
default_torrent_page_size = 10
max_torrent_page_size = 30

[tracker_statistics_importer]
port = 3_002
torrent_info_update_interval = 3_600
```
